name: Build and Deploy

# This workflow runs on pushes to the master branch
on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  ARTIFACT_REGISTRY_URL: "us-central1-docker.pkg.dev"
  IMAGE_NAME: "iris_fast_api"
  DEPLOYMENT_NAME: "demo-iris-workload" # As defined in your deployment.yaml

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    # Add permissions for GitHub's OIDC token
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Google Cloud Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true    

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY_URL }}

    - name: Build Docker Image
      run: |
        docker build \
          --tag "${{ env.ARTIFACT_REGISTRY_URL }}/${{ env.GCP_PROJECT_ID }}/my-first-repo/${{ env.IMAGE_NAME }}:${{ github.sha }}" \
          --tag "${{ env.ARTIFACT_REGISTRY_URL }}/${{ env.GCP_PROJECT_ID }}/my-first-repo/${{ env.IMAGE_NAME }}:latest" \
          .

    - name: Push Docker Image to Artifact Registry
      run: |
        docker push "${{ env.ARTIFACT_REGISTRY_URL }}/${{ env.GCP_PROJECT_ID }}/my-first-repo/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        docker push "${{ env.ARTIFACT_REGISTRY_URL }}/${{ env.GCP_PROJECT_ID }}/my-first-repo/${{ env.IMAGE_NAME }}:latest"

    - name: Get GKE Credentials
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: ${{ env.GKE_CLUSTER_NAME }}
        location: ${{ env.GKE_ZONE }}

    - name: Deploy to GKE
      run: |
        echo "Updating deployment with new image..."
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
          pre-oppe=${{ env.ARTIFACT_REGISTRY_URL }}/${{ env.GCP_PROJECT_ID }}/my-first-repo/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Verify Deployment
      run: |
        echo "Waiting for rollout to complete..."
        kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}

